### ISSUE TITLE
More screen changes

### ISSUE THREAD

**Issue by mkobar** [theirfanirfi/angular-ecom#11]
Home page -
Move Avatar button to top button and link to drop down menu  - like in Fiverr.com!
Move profile link to Avatar drop down menu  - like in Fiverr.com!
Move logout button to the Avatar drop down menu (at bottom) - like in Fiverr.com!

Checkout page
Remove company
Add USA to country dropdown
Only show state dropdown if country is USA
Validate email address is a correct email format

Cart
Looks like the grand total is not reset to 0 when the cart is purchased. It should be set to 0.

**Comment by theirfanirfi** [comment]
fixed.
