### ISSUE TITLE
cart amount +/- buttons break the cart total

### ISSUE THREAD

**Issue by mkobar** [theirfanirfi/angular-ecom#13]
cart amount +/- buttons break the cart total

<img width="922" alt="2022-04-11 08_58_33-EcomApp" src="https://user-images.githubusercontent.com/2513273/162751508-b3204b98-f8b9-44a9-9f54-e3a6e2f267e7.png">
<img width="922" alt="2022-04-11 08_57_45-EcomApp" src="https://user-images.githubusercontent.com/2513273/162751509-2e2bf483-6e29-4041-ac46-66ff003cc351.png">
<img width="922" alt="2022-04-11 08_57_18-EcomApp" src="https://user-images.githubusercontent.com/2513273/162751511-872d1c0e-23cd-4010-849d-7cb257edc27b.png">
<img width="922" alt="2022-04-11 09_03_45-EcomApp" src="https://user-images.githubusercontent.com/2513273/162751512-6744a5ef-926c-4500-bd7d-6fb389fea45d.png">

**Comment by theirfanirfi** [comment]
fixed.
