### ISSUE TITLE
in smartphone size, the payment page looks bad, as the fields are too small

### ISSUE THREAD

**Issue by mkobar** [theirfanirfi/angular-ecom#14]
in smartphone size, payment page looks bad - as the fields are too small

<img width="375" alt="2022-04-11 09_19_07-EcomApp" src="https://user-images.githubusercontent.com/2513273/162751929-bcb4eebc-5b4b-47b7-8483-0482f9173131.png">

**Comment by mkobar** [comment]
The middle box should be the width of the screen (or at least double the current size).

**Comment by theirfanirfi** [comment]
fixed
