### ISSUE TITLE
heart icon as filled in the wishlist and allow the user to remove it if the full heart icon is selected

### ISSUE THREAD

**Issue by mkobar** [theirfanirfi/angular-ecom#15]
show the heart icon as filled if the item is already in the wishlist and allow the user to remove it from the wishlist if the full heart icon is selected (like most favorites)

**Comment by theirfanirfi** [comment]
please watch the video, i have sent you a few days back. For doing so, we would need to move the products to a database as well. This functionality will work fine with a (relational) database. I will issue a query by joining the products and wishlist. It will be done easy. Now, the products don't come from a database and neither I can make a custom query. So, this is the issue.
