### ISSUE TITLE
Card number field is still too small on smartphone sized-screen

### ISSUE THREAD

**Issue by mkobar** [theirfanirfi/angular-ecom#17]
card number field is still too small on smartphone sized-screen. And now CCV field is too large on both browser and smartphone.  And the wire transfer option is gone, which was nice to have.  Compare attached screen shots with screenshot in issue 14.

<img width="375" alt="2022-04-21 09_51_17-EcomApp" src="https://user-images.githubusercontent.com/2513273/164475356-b1ee6406-ca0e-41ef-a833-6c62a08fff95.png">

<img width="950" alt="2022-04-21 09_53_04-EcomApp" src="https://user-images.githubusercontent.com/2513273/164475449-4b35ebb9-6778-4954-a997-5361cc9ad942.png">

**Comment by theirfanirfi** [comment]
fixed. Please check.
