### ISSUE TITLE
Card number field is now too big on both smartphone sized-screen and browser

### ISSUE THREAD

**Issue by mkobar** [theirfanirfi/angular-ecom#18]
Card number field is now too big on both smartphone sized-screen and browser. As is the month, date and CCV fields (for max length needed for each field see screen shot below):

<img width="412" alt="2022-04-26 09_01_01-EcomApp" src="https://user-images.githubusercontent.com/2513273/165306393-16200d2c-9c09-48c4-86af-d4b247afebdc.png">

It should look more like the "old" version (see screen shot below):

<img width="310" alt="2022-04-26 09_16_13-EcomApp" src="https://user-images.githubusercontent.com/2513273/165308619-dcea5218-842c-4165-8531-9b49a0608fc0.png">

This version also shows all the cards in the icon and allows the bank transfer method - which we do still need.
We need the "old" version on both the browser and the smartphone screen.

**Comment by mkobar** [comment]
Note that the max size for the credit card number is 19 digits, but usually 15 or 16 digits
The max size for month is 2 digits
The max size for year is 4 digits (and we should show YYYY)
The max size for the CVV is 4 digits, but usually 3 digits

**Comment by theirfanirfi** [comment]
fixed. Please check it. If it still didn't work, I will have to change the payment template as a whole.
