### ISSUE TITLE
Home/Products page needs to be data driven

### ISSUE THREAD

**Issue by mkobar** [theirfanirfi/angular-ecom#2]
Home/Products page needs to be data driven (populated from a table).  The table should include all the data displayed, including a URL for the product picture(s) - full and thumbnail.  Amount (number of items) can also be in the page.

Then both the Home/Products page and the Product Detail/quick-shop dialog will both be generated from the data.

Use the same data that is currently in the page for now.

This will also allow the show number pull-down and sort by pull-down to really work.

Also need to fix the shop-grid button to link back to the home/products page and support the shop-list button (and new page).

**Comment by theirfanirfi** [comment]
fixed.

**Comment by mkobar** [comment]
Fixed:
Home/Products page needs to be data driven (populated from a table). 

Use the same data that is currently in the page for now.

Not fixed:

 The table should include all the data displayed, **including a URL for the product picture(s) - full and thumbnail. Amount (number of items) can also be in the page**.

Then both the Home/Products page and the Product Detail/quick-shop dialog will both be generated from the data.
**Price and description need to come from the table for Product Detail/quick-shop dialog**

**This will also allow the show number pull-down and sort by pull-down to really work**.

**Also need to fix the shop-grid button to link back to the home/products page and support the shop-list button (and new page)**.
