### ISSUE TITLE
Make wishlist work

### ISSUE THREAD

**Issue by mkobar** [theirfanirfi/angular-ecom#4]
Make wishlist work
  top menu wishlist should show list of products that the user added to wishlist
  User should be able to add from wishlist to cart
  User should be able to delete product from wishlist

Detail products/quick shop dialog
  wishlist button should add to wishlist

Home/Products page - product menu
  wishlist button should add to wishlist

**Comment by mkobar** [comment]
Whishlist still does not work for me.  I do get an alert that tells me things have been added to the wishlist but never see anything in the wishlist.

**Comment by theirfanirfi** [comment]
fixed.
