### ISSUE TITLE
Profile/account data should be saved and auto-populated

### ISSUE THREAD

**Issue by mkobar** [theirfanirfi/angular-ecom#5]
Profile page
Should fill in name and email address from profile table

Checkout page
Should fill in name and email from profile page table
Create account should work - additional data can be saved in profile table
Remove company pull-down

**Comment by mkobar** [comment]
I think the best way to do this is to allow a login on the home page but require either a login or an account registration on checkout.  We should add all the fields in the checkout page to the registration, so that the user can just login at that time and not need to fill in any forms.

this would also add all the registration/checkout fields to the profile page too.

Also the login/account registration dialog should be a modal (so it can popup on top of the current page).

I think this would work better.

**Comment by theirfanirfi** [comment]
fixed.
