### ISSUE TITLE
Change login and register text box font colors to something much brighter - I cannot see them

### ISSUE THREAD

**Issue by mkobar** [theirfanirfi/angular-ecom#6]
Change login and register text box font colors to something much brighter - I cannot see them.

Also fix the title color and do not make the bottom button dark before hover.

And need to add the "forgot password" link under the password text box.  This functionality is supported in Firebase.
We should verify the email address with Firebase too.

**Comment by theirfanirfi** [comment]
fixed.

**Comment by mkobar** [comment]
Fixed:

Change login and register text box font colors to something much brighter - I cannot see them.

Also fix the title color and do not make the bottom button dark before hover.

And need to add the "forgot password" link under the password text box. This functionality is supported in Firebase.

Not Fixed:
We should verify the email address with Firebase too. **During sign-up. Firebase supports this too.**
