### ISSUE TITLE
First page should be Home/Products page, not login page (like amazon)

### ISSUE THREAD

**Issue by mkobar** [theirfanirfi/angular-ecom#8]
First page should be Home/Products page, not login page (like amazon).  Login should be optional until after checkout page.
Then if not logged in, pop the login dialog.

Only by logging in or registering for an account can you continue to payment page.

**Comment by theirfanirfi** [comment]
fixed

**Comment by mkobar** [comment]
Fixed:

First page should be Home/Products page, not login page (like amazon). Login should be optional until after checkout page.
**Then if not logged in,** pop the login dialog.

Only by logging in or registering for an account can you continue to payment page.

Not Fixed:  
**The logout button at the top should say login if not logged in.  Logout need to work.  This is supported in Firebase.**

**The login dialog, if from the checkout button should return to the checkout page, not the home page.**

**The login page should only pop if the user is not logged in - or the user logs out.**
