### ISSUE TITLE
In responsive mode (like on a cell phone) the wishlist, Avatar and cart buttons are all missing.

### ISSUE THREAD

**Issue by mkobar** [theirfanirfi/angular-ecom#9]
In responsive mode (like on a cell phone) the wishlist, Avatar and cart buttons are all missing.

Without the cart button nothing can be purchased.

Perhaps when you move all three buttons to the top menu this will be fixed.  Then this is not an issue.

**Comment by theirfanirfi** [comment]
fixed.
